language: generic
sudo: required  # Specifying we will need root permissions in the system.
services:
  - docker  # We need docker service.

before_install:  # Commands that should be run before run our test suits.
  - docker build -t testcontainer -f Dockerfile.dev .

script:  # series of commands that should be run in order to execute our test suit.
  - docker run -e CI=true testcontainer npm run test
